### ISSUE TITLE
比原链 Bytom

### ISSUE THREAD

**Issue by ChrisLinn** [chaozh/awesome-blockchain-cn#10]
巴比特的专注于数字资产和线下资产联接,登记,转换,交易的公有链。和以太坊相比保留了比特币中的utxo支持并行，并加入轻量虚拟机专注支持金融产品的智能合约，故对金融产品的智能合约更加高效。

repo: https://github.com/Bytom/bytom
技术白皮书: https://bytom.io/BytomWhitePaperV1.0_En.pdf
商业白皮书: https://bytom.io/BytomWhitePaperV1.0_Economic_en.pdf

**Comment by chaozh** [comment]
好像不怎么活跃啊

**Comment by ChrisLinn** [comment]
star 比 CITA 多，
项目还在开发中所以 master branch 的 commit 不是最新的，
主要活跃在 dev branch

**Comment by HAOYUatHZ** [comment]
@chaozh 

star 比 CITA 多，
项目还在开发中所以 master branch 的 commit 不是最新的，
主要活跃在 dev branch

**Comment by chaozh** [comment]
已经添加
