### ISSUE TITLE
厉害了，我的md程序员

### ISSUE THREAD

**Issue by tonyxyl** [chaozh/awesome-blockchain-cn#15]
just a joke!

**Comment by pychango** [comment]
> just a joke!

this is test, to pritice github use . sorry.

**Comment by chaozh** [comment]
区块链这块知识比较新也比较散，市面上缺少一个，个人感觉这个repo还是蛮有用的。

**Comment by tonyxyl** [comment]
玩笑哈，有用的，已star。
