### ISSUE TITLE
Translate to English

### ISSUE THREAD

**Issue by vitalets** [chaozh/awesome-blockchain-cn#2]
Hi I feel it's a great repo, it would be nice to translate it in English.
Thanks!

**Comment by saiKumarGanji** [comment]
All the blog posts under the project are in chinese.
It wouldnt help much even if the project gets translated into english.

**Comment by vitalets** [comment]
@saiKumarGanji 
I agree about blogposts but I found several links to projects/sdk/videos that are in English. for example this one:

> * [Create your own crypto-currency](https://www.ethereum.org/token) 来自以太坊官方的代币创建教程

It would be very helpful to have a short description of these links in English as well.
I think you are doing a great thing and many people around the world are interested in this topic.

**Comment by Bgumel** [comment]
let's create another English version of this list , not all of the resources are in Chinese language

**Comment by zulfahrizal** [comment]
Very good

**Comment by amor520** [comment]
cool

**Comment by xx77xx** [comment]
您好，我已经成功收到了邮件!尽快给您回复。
