### ISSUE TITLE
区块链工程师面试宝典

### ISSUE THREAD

**Issue by ChrisLinn** [chaozh/awesome-blockchain-cn#21]
https://github.com/ChrisLinn/blockchain-cheatsheet

持续更新中

**Comment by chaozh** [comment]
目前还没什么内容，暂不收录

**Comment by ChrisLinn** [comment]
题目还是不少的

很多答案没整理出来 每道题目就一行 看起来当然不长 像 **比特币设计思想** 那一节搞清楚对深入理解很有帮助
