### ISSUE TITLE
区块链详解入门文章

### ISSUE THREAD

**Issue by CharlesLiuyx** [chaozh/awesome-blockchain-cn#26]
项目名称：个人博客Fancy排版的区块链入门文章

[【区块链】共识算法与如何解决拜占庭将军问题](https://charlesliuyx.github.io/2018/03/03/%E3%80%90%E5%8C%BA%E5%9D%97%E9%93%BE%E3%80%91%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%E6%8B%9C%E5%8D%A0%E5%BA%AD%E5%B0%86%E5%86%9B%E9%97%AE%E9%A2%98/)
白话文讲懂什么是拜占庭将军问题并且总结了现在比较常见的共识算法

[【区块链】一文看懂区块链：一步一步发明比特币](https://charlesliuyx.github.io/2017/09/24/%E4%B8%80%E6%96%87%E5%BC%84%E6%87%82%E5%8C%BA%E5%9D%97%E9%93%BE-%E4%BB%A5%E6%AF%94%E7%89%B9%E5%B8%81%E4%B8%BA%E4%BE%8B/)
白话文讲解区块链背后原理，了解什么是区块链，小白也能看懂

[【区块链】比特币与金融、ICO和监管](https://charlesliuyx.github.io/2017/09/25/%E5%8C%BA%E5%9D%97%E9%93%BE%EF%BC%88%E6%AF%94%E7%89%B9%E5%B8%81%EF%BC%89%E4%B8%8E%E9%87%91%E8%9E%8D/)
什么是ICO？比特币与传统金融的一些思考

**Comment by chaozh** [comment]
文章挺不错的，陆续收录
