### ISSUE TITLE
基于区块链的电子投票系统

### ISSUE THREAD

**Issue by yfgeek** [chaozh/awesome-blockchain-cn#4]
项目地址：https://github.com/yfgeek/BlockVotes
项目演示视频：https://www.youtube.com/watch?v=4c6pQg3q4Vc
本项目为本人论文期间所做项目，基于ring signature 和blockchain，使用bitcoin的主链或testnet链做的电子投票系统。

希望能够加入贵清单，为开源项目贡献一份力量！

**Comment by chaozh** [comment]
界面设计还可以，但是没看到核心的与区块链交互的代码？

**Comment by yfgeek** [comment]
@chaozh 用公用的api与比特币做的交互

**Comment by chaozh** [comment]
在哪个文件 我学习下

**Comment by lezi1022** [comment]
没看到跟blockchain交互的代码

**Comment by yfgeek** [comment]
@chaozh @lezi1022 通过js与第三方API交互
https://github.com/yfgeek/BlockVotes/tree/master/public/assets/scripts 
目录下有很多，举例
https://github.com/yfgeek/BlockVotes/blob/master/public/assets/scripts/ea-fee.js
