### ISSUE TITLE
Hi～请问有没有兴趣来W3c.Group区块链技术社区创建您的专属小组？

### ISSUE THREAD

**Issue by isdotjim** [chaozh/awesome-blockchain-cn#46]
您可以做什么：在W3c.Group社区创建小组，转发或输出和区块链技术相关的内容，和加入小组的成员关注者进行互动。

这样做的价值：帮助更多的开发者学习区块链技术，同时提升您的社区知名度，对您感兴趣的开发者或潜在合作者、投资人能主动找到您。

官网以及介绍：[https://w3c.group/about](https://w3c.group/about)

W3c.Group正在冷启动，欢迎通过社区内私信或微信联系瓦工，了解并成为W3c.Group核心共建者

**Comment by why168** [comment]
怎么参与?我能做什么？主要写Android、Java api  https://github.com/why168

瓦工 <notifications@github.com> 于2019年7月22日周一 下午2:47写道：
