### ISSUE TITLE
大佬好，readme里面的TUTORIAL 教程——mac配置以太坊本地开发环境的链接失效了

### ISSUE THREAD

**Issue by FOWnglp** [chaozh/awesome-blockchain-cn#60]
readme里面的TUTORIAL 教程——mac配置以太坊本地开发环境的链接失效了

https://my.oschina.net/wtsoftware/blog/782057

<img width="423" alt="image" src="https://user-images.githubusercontent.com/53960028/158248529-168304ce-d9b3-4fb1-b49c-ebc966fe2552.png">

**Comment by xx77xx** [comment]
您好，我已经成功收到了邮件!尽快给您回复。

**Comment by querqing** [comment]
来信均悉。
