### ISSUE TITLE
Add  blockchair.com and 3xpl.com to the block explorer

### ISSUE THREAD

**Issue by martgil** [chaozh/awesome-blockchain-cn#69]
Hello team,

I would like to suggest https://3xpl.com and https://blockchair.com be added to the block explorer list.

Blockchair.com is a Universal blockchain explorer and search engine, and 3xpl.com is an ad-free, fast universal explorer.

I hope this is something the team is interested in.

**Comment by querqing** [comment]
来信均悉。

**Comment by xx77xx** [comment]
您好，我已经成功收到了邮件!尽快给您回复。
