### ISSUE TITLE
CITA

### ISSUE THREAD

**Issue by u2** [chaozh/awesome-blockchain-cn#7]
CITA是一个面向企业级应用的支持智能合约的区块链框架。

白皮书：https://github.com/cryptape/cita-whitepaper
代码仓库：https://github.com/cryptape/cita

**Comment by NewLionwang** [comment]
去中心化到底好不好？

**Comment by u2** [comment]
去中心化好不好，取决于场景。而现在区块链除了在技术方面去探索，还需要社会学家，经济学家，企业家等各方面的专家去探索业务方面的可能性。区块链不是单纯的去中心，而是有多种可能，包括多中心，一个强中心多个弱中心等等。现在全球众多行业都在走向寡头，比如阿里，网约车等。垄断最大的问题在于独裁，在一定程度上遏制了创新。这是区块链可能存在的一个场景。另外比如银行间的清结算等等，更符合多中心的场景。

追求完全的中心化，只是人类的一个政治诉求而已，在兼顾技术和效率的情况下，不一定是最优的。

**Comment by chaozh** [comment]
added
